import re


def generate_dashboard():
    with open('AUDIT-LOG.md', 'r') as f:
        content = f.read()

    # Basic stats
    total = len(re.findall(r'^## Audit:', content, re.MULTILINE))
    refused = content.count('Allowed: false')
    approved = content.count('Allowed: true')
    refusal_rate = round((refused / total * 100), 1) if total > 0 else 0

    # Top reasons
    reasons = re.findall(r'Reason: (.+)', content)
    from collections import Counter
    top_reasons = Counter(reasons).most_common(8)

    # Recent activity (last 10 entries)
    recent = re.findall(r'^## Audit:.*', content, re.MULTILINE)[-10:][::-1]

    from datetime import datetime

    # Build dashboard markdown
    dashboard = f"""# Audit Dashboard

**Last Updated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

## Summary

| Metric            | Value      |
|-------------------|------------|
| Total Audits      | {total}    |
| Refusals          | {refused}  |
| Approvals         | {approved} |
| Refusal Rate      | {refusal_rate}% |

## Top Refusal Reasons

| Reason | Count |
|--------|-------|
"""

    for reason, count in top_reasons:
        dashboard += f"| {reason} | {count} |\n"

    dashboard += "\n## Recent Activity\n\n"
    for entry in recent:
        dashboard += f"- {entry}\n"

    dashboard += "\n---\n*This dashboard is automatically generated by GitHub Actions.*\n"

    with open('AUDIT-DASHBOARD.md', 'w') as f:
        f.write(dashboard)

    # Also generate JSON for the web dashboard
    import json
    data = {
        "last_updated": datetime.utcnow().isoformat() + "Z",
        "total_audits": total,
        "refusals": refused,
        "approvals": approved,
        "refusal_rate": refusal_rate,
        "top_reasons": [{"reason": r[0], "count": r[1]} for r in top_reasons]
    }
    with open('docs/dashboard-data.json', 'w') as f:
        json.dump(data, f, indent=2)

    print("Dashboard files generated successfully")


if __name__ == "__main__":
    generate_dashboard()